# Generated by Django 2.0.7 on 2020-01-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='private_key',
            field=models.BinaryField(blank=True, null=True, unique=True),
        ),
    ]
