# Generated by Django 2.0.7 on 2020-01-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200118_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contain',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
