# Generated by Django 2.0.7 on 2020-01-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200119_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sign_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
