# Generated by Django 2.0.7 on 2020-01-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200120_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.CharField(default='Topic', max_length=100),
        ),
    ]
